### ISSUE TITLE
We need custom executor

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/phie#57] opened 2023-05-19 16:40 UTC
We need to add a file to the bin directory, which will take as input the name of the file where the code in phi-calculus is written. It will execute it, output the result of dataization and compare with it if there is a correct answer in the file.

**Comment by EugeneDar** [comment] 2023-05-19 16:40
@yegor256 what do you think?

**Comment by yegor256** [comment] 2023-05-19 22:29
Duplicate of #23

**Closed by yegor256** 2023-05-19 22:29 UTC
